require("yiyuanh.remap")
require("yiyuanh.set")
require("yiyuanh.lazy")
require("yiyuanh.treesitter")
require("yiyuanh.lsp")
require("yiyuanh.telescope")
require("yiyuanh.colorizer")
require("yiyuanh.comment")

vim.cmd("colorscheme catppuccin-latte")
